// NOTE: Do not edit this file directly, edit your server's config.json
// See http://docs.sparklinlabs.com/en/collaborating-in-real-time
export default {
  mainPort: 4237,
  buildPort: 4238,
  password: "",
  maxRecentBuilds: 50
}
